image:
  repository: ghcr.io/gethomepage/homepage
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingressTargets:
  myaddr:
    host: lmtlmt.myaddr.io
    certResolver: myaddr
  duckdns:
    host: epricesx.duckdns.org
    certResolver: letsencrypt
  freemyip:
    host: lmtu.freemyip.com
    certResolver: freemyip

config:
  services:
    - Infrastructure:
        - Argo CD:
            icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/argocd.png
            href: https://argo.lmtlmt.myaddr.io
            description: GitOps Deployment
        - Traefik:
            icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/traefik.png
            href: https://traefik.lmtlmt.myaddr.io/dashboard/
            description: Ingress Controller
        - Nextcloud:
            icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/nextcloud.png
            href: https://nextcloud.lmtlmt.myaddr.io
            description: Cloud Storage

    - Media:
        - Jellyfin:
            icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/jellyfin.png
            href: https://jellyfin.lmtlmt.myaddr.io
            description: Media Server
        - Sonarr:
            icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/sonarr.png
            href: https://sonarr.lmtlmt.myaddr.io
            description: TV Shows
        - Radarr:
            icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/radarr.png
            href: https://radarr.lmtlmt.myaddr.io
            description: Movies
        - Prowlarr:
            icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/prowlarr.png
            href: https://prowlarr.lmtlmt.myaddr.io
            description: Indexer Manager
        - qBittorrent:
            icon: https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/qbittorrent.png
            href: https://qbittorrent.lmtlmt.myaddr.io
            description: Torrent Client

  widgets: []

  settings:
    title: Home Lab
    background: "#24273a"
    cardBlur: sm
    theme: dark
    color: slate
    layout:
      Infrastructure:
        style: row
        columns: 3
      Media:
        style: row
        columns: 5
