{{- range .Values.ingresses }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .name }}-tailscale
  namespace: {{ .namespace }}
  annotations:
    tailscale.com/funnel: "true"
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
    - {{ .host }}
  defaultBackend:
    service:
      name: {{ .serviceName }}
      port:
        number: {{ .port }}
{{- end }}
