apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "common.labels.selector" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.labels.selector" . | nindent 8 }}
    spec:
      {{- if .Values.uploadAssistant.securityContext }}
      securityContext:
        {{- toYaml .Values.uploadAssistant.securityContext | nindent 8 }}
      {{- end }}
      containers:
        - name: upload-assistant
          image: "{{ .Values.uploadAssistant.image.repository }}:{{ .Values.uploadAssistant.image.tag }}"
          imagePullPolicy: {{ .Values.uploadAssistant.image.pullPolicy }}
          args: ["--webui", "0.0.0.0:5000"]
          ports:
            - name: http
              containerPort: 5000
              protocol: TCP
          env:
            {{- range $key, $value := .Values.uploadAssistant.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          volumeMounts:
            {{- if .Values.uploadAssistant.persistence.config.enabled }}
            - name: config-volume
              mountPath: /Upload-Assistant/data
              subPath: data
            - name: config-volume
              mountPath: /Upload-Assistant/tmp
              subPath: tmp
            - name: config-volume
              mountPath: /root/.config/upload-assistant
              subPath: webui-auth
            {{- end }}
            {{- if .Values.uploadAssistant.persistence.downloads.enabled }}
            - name: downloads-volume
              mountPath: /downloads
            {{- end }}
            {{- range .Values.uploadAssistant.clients }}
            - name: {{ .name }}-config-volume
              mountPath: /BT_backup/{{ .name }}
              subPath: qBittorrent/BT_backup
              readOnly: true
            {{- end }}
      volumes:
        {{- if .Values.uploadAssistant.persistence.config.enabled }}
        - name: config-volume
          persistentVolumeClaim:
            claimName: {{ .Values.uploadAssistant.persistence.config.existingClaim }}
        {{- end }}
        {{- if .Values.uploadAssistant.persistence.downloads.enabled }}
        - name: downloads-volume
          persistentVolumeClaim:
            claimName: {{ .Values.uploadAssistant.persistence.downloads.existingClaim }}
        {{- end }}
        {{- range .Values.uploadAssistant.clients }}
        - name: {{ .name }}-config-volume
          persistentVolumeClaim:
            claimName: {{ .claimName }}
        {{- end }}
