apiVersion: v1
kind: Secret
metadata:
  name: media-slskd-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
{{- range $key, $val := .Values.slskd.secretData }}
  {{ $key }}: {{ $val | quote }}
{{- end }}
