apiVersion: v1
kind: ConfigMap
metadata:
  name: cronjob-scripts
  namespace: {{ .Release.Namespace }}
data:
{{- range $name, $config := .Values.jobs }}
  {{ $name }}.sh: |
{{ tpl $config.script $ | indent 4 }}
{{- end }}
