{{- range $name, $config := .Values.jobs }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
spec:
  schedule: {{ $config.schedule | quote }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          {{- if $config.securityContext }}
          securityContext:
            {{- toYaml $config.securityContext | nindent 12 }}
          {{- end }}
          containers:
          - name: runner
            image: {{ $config.image }}
            command: ["/bin/sh", "/scripts/{{ $name }}.sh"]
            {{- if $config.containerSecurityContext }}
            securityContext:
              {{- toYaml $config.containerSecurityContext | nindent 14 }}
            {{- end }}
            {{- with $config.env }}
            env:
              {{- toYaml . | nindent 14 }}
            {{- end }}
            volumeMounts:
            - name: scripts
              mountPath: /scripts
              readOnly: true
            {{- if $config.volumeMounts }}
              {{- toYaml $config.volumeMounts | nindent 12 }}
            {{- end }}
          volumes:
          - name: scripts
            configMap:
              name: cronjob-scripts
              defaultMode: 0755
          {{- if $config.volumes }}
            {{- toYaml $config.volumes | nindent 10 }}
          {{- end }}
{{- end }}
