{{- range $name, $config := .Values.jobs }}
{{- if $config.runOnStartup }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $name }}-on-sync
  namespace: {{ $.Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    spec:
      restartPolicy: OnFailure
      {{- if $config.securityContext }}
      securityContext:
        {{- toYaml $config.securityContext | nindent 8 }}
      {{- end }}
      containers:
      - name: runner
        image: {{ $config.image }}
        command: ["/bin/sh", "/scripts/{{ $name }}.sh"]
        {{- if $config.containerSecurityContext }}
        securityContext:
          {{- toYaml $config.containerSecurityContext | nindent 10 }}
        {{- end }}
        {{- with $config.env }}
        env:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: scripts
          mountPath: /scripts
          readOnly: true
        {{- if $config.volumeMounts }}
          {{- toYaml $config.volumeMounts | nindent 8 }}
        {{- end }}
      volumes:
      - name: scripts
        configMap:
          name: cronjob-scripts
          defaultMode: 0755
      {{- if $config.volumes }}
        {{- toYaml $config.volumes | nindent 6 }}
      {{- end }}
{{- end }}
{{- end }}