apiVersion: v1
kind: Secret
metadata:
  name: operator-oauth
  namespace: tailscale
type: Opaque
stringData:
  TAILNET: "platy-python.ts.net"
  client_id: "kSC5Es3VV911CNTRL"
  client_secret: "tskey-client-kSC5Es3VV911CNTRL-Y6NP6zQau6iNWSfMqmmf6idibafhucgvT"
