apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-postgres
  namespace: core
spec:
  project: default
  source:
    repoURL: https://github.com/tu-leminh/argohome
    targetRevision: HEAD
    path: apps/infra/postgres-operator
  destination:
    server: https://kubernetes.default.svc
    namespace: infra
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true