apiVersion: v1
kind: Secret
metadata:
  name: github-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/tu-leminh/argohome
  password: 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
  username: tu-leminh
