apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: {{ .Values.q1.service.type | default "ClusterIP" }}
  {{- if .Values.q1.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.q1.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.q1.service.port }}
      targetPort: webui
      protocol: TCP
      name: webui
    - port: 6881
      targetPort: torrent-tcp
      protocol: TCP
      name: torrent-tcp
    - port: 6881
      targetPort: torrent-udp
      protocol: UDP
      name: torrent-udp
  selector:
    {{- include "common.labels.selector" . | nindent 4 }}
