{{- range $name, $content := .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
type: Opaque
data:
  {{- toYaml $content.data | nindent 2 }}
{{- end }}
