apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: {{ .Values.sftpgo.service.type | default "ClusterIP" }}
  {{- if .Values.sftpgo.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.sftpgo.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.sftpgo.service.sftpPort }}
      targetPort: sftp
      protocol: TCP
      name: sftp
    - port: {{ .Values.sftpgo.service.httpPort }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.sftpgo.service.webdavPort }}
      targetPort: webdav
      protocol: TCP
      name: webdav
  selector:
    {{- include "common.labels.selector" . | nindent 4 }}
