apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: home-pool
  namespace: {{ .Release.Namespace }}
spec:
  addresses:
  - 192.168.1.111/32  # Reserved for Traefik
  - 192.168.1.112/32  # Reserved for ArgoCD
  - 192.168.1.113-192.168.1.200  # Available for other services
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: home-l2
  namespace: {{ .Release.Namespace }}
spec:
  ipAddressPools:
  - home-pool
