apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: home-pool
  namespace: {{ .Release.Namespace }}
spec:
  addresses:
  - 192.168.1.100-192.168.1.110  # Available range
  - 192.168.1.113-192.168.1.200  # Available range excluding 111 and 112
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: home-l2
  namespace: {{ .Release.Namespace }}
spec:
  ipAddressPools:
  - home-pool
