jobs:
  duckdns-updater:
    schedule: "*/20 * * * *"
    image: curlimages/curl:latest
    domain: epricesx
    env:
      - name: DUCKDNS_TOKEN
        valueFrom:
          secretKeyRef:
            name: duckdns-secret
            key: DUCKDNS_TOKEN

  freemyip-updater:
    schedule: "5-59/20 * * * *"
    image: curlimages/curl:latest
    domain: lmtu.freemyip.com
    env:
      - name: FREEMYIP_TOKEN
        valueFrom:
          secretKeyRef:
            name: freemyip-secret
            key: FREEMYIP_TOKEN

  myaddr-updater:
    schedule: "10-59/20 * * * *"
    image: curlimages/curl:latest
    env:
      - name: MYADDR_KEY
        valueFrom:
          secretKeyRef:
            name: myaddr-secret
            key: MYADDR_KEY

