apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-tailscale
  annotations:
    tailscale.com/funnel: "true"
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
    - argo
  defaultBackend:
    service:
      name: argocd-server
      port:
        number: 443
