apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server-duckdns
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`argo.epricesx.duckdns.org`)
    kind: Rule
    services:
    - name: argocd-server
      port: 80
  tls:
    certResolver: letsencrypt
    domains:
    - main: argo.epricesx.duckdns.org
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server-freemyip
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`argo.lmtu.freemyip.com`)
    kind: Rule
    services:
    - name: argocd-server
      port: 80
  tls:
    certResolver: freemyip
    domains:
    - main: argo.lmtu.freemyip.com