apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: argocd-transport
  namespace: {{ .Release.Namespace }}
spec:
  insecureSkipVerify: true
{{- range $name, $target := .Values.ingressTargets }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: argocd-server-{{ $name }}
  namespace: {{ $.Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ $target.host }}`)
    kind: Rule
    services:
    - name: argocd-server
      port: 443
      scheme: https
      serversTransport: argocd-transport
    middlewares:
      - name: argocd-headers
  {{- if $target.certResolver }}
  tls:
    certResolver: {{ $target.certResolver }}
  {{- end }}
{{- end }}