apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: autobrr-tailscale
  annotations:
    tailscale.com/funnel: "true"
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
    - autobrr
  defaultBackend:
    service:
      name: {{ include "common.names.fullname" . }}
      port:
        number: 7474