nodeName: "dell"
mounts:
  # Media Volumes (Shared)
  - name: media-shared-downloads
    path: /data/apps/media/shared/downloads
    size: 500Gi
    accessMode: ReadWriteMany
  - name: media-shared-movies
    path: /data/apps/media/shared/movies
    size: 500Gi
    accessMode: ReadWriteMany
  - name: media-shared-shows
    path: /data/apps/media/shared/shows
    size: 500Gi
    accessMode: ReadWriteMany

  # App Configs (Media)
  - name: media-sonarr-config
    path: /data/apps/media/sonarr/config
    size: 1Gi
  - name: media-radarr-config
    path: /data/apps/media/radarr/config
    size: 1Gi
  - name: media-transmission-config
    path: /data/apps/media/transmission/config
    size: 1Gi
  - name: media-t1-config
    path: /data/apps/media/t1/config
    size: 1Gi
  - name: media-t2-config
    path: /data/apps/media/t2/config
    size: 1Gi
  - name: media-t3-config
    path: /data/apps/media/t3/config
    size: 1Gi
  - name: media-t4-config
    path: /data/apps/media/t4/config
    size: 1Gi
  - name: media-t5-config
    path: /data/apps/media/t5/config
    size: 1Gi
  - name: media-deluge-config
    path: /data/apps/media/deluge/config
    size: 1Gi
  - name: media-jellyfin-config
    path: /data/apps/media/jellyfin/config
    size: 100Gi
  - name: media-prowlarr-config
    path: /data/apps/media/prowlarr/config
    size: 1Gi
  - name: media-bazarr-config
    path: /data/apps/media/bazarr/config
    size: 1Gi
  - name: media-autobrr-config
    path: /data/apps/media/autobrr/config
    size: 1Gi
  - name: media-qbittorrent-config
    path: /data/apps/media/qbittorrent/config
    size: 1Gi

  # rTorrent
  - name: media-rtorrent-data
    path: /data/apps/media/rtorrent/data
    size: 5Gi
  - name: media-rtorrent-passwd
    path: /data/apps/media/rtorrent/passwd
    size: 100Mi

  # oCIS
  - name: owncloud-ocis-config
    namespace: ocis
    path: /data/apps/ocis/owncloud-ocis/config
    size: 1Gi
  - name: owncloud-ocis-data
    namespace: ocis
    path: /data/apps/ocis/owncloud-ocis/data
    size: 500Gi
    accessMode: ReadWriteMany

  # Infrastructure
  - name: infra-traefik-config
    namespace: infra
    path: /data/apps/infra/traefik/config
    size: 1Gi
