nodeName: "dell"
mounts:
  # Media Volumes (Shared)
  - name: media-shared-downloads
    path: /data/apps/media/shared/downloads
    size: 500Gi
    accessMode: ReadWriteMany
  - name: media-shared-movies
    path: /data/apps/media/shared/movies
    size: 500Gi
    accessMode: ReadWriteMany
  - name: media-shared-shows
    path: /data/apps/media/shared/shows
    size: 500Gi
    accessMode: ReadWriteMany

  # App Configs (Media)
  - name: media-sonarr-config
    path: /data/apps/media/sonarr/config
    size: 1Gi
  - name: media-radarr-config
    path: /data/apps/media/radarr/config
    size: 1Gi
  - name: media-qbittorrent-config
    path: /data/apps/media/qbittorrent/config
    size: 1Gi
  - name: media-jellyfin-config
    path: /data/apps/media/jellyfin/config
    size: 100Gi
  - name: media-prowlarr-config
    path: /data/apps/media/prowlarr/config
    size: 1Gi
  - name: media-bazarr-config
    path: /data/apps/media/bazarr/config
    size: 1Gi

  # Nextcloud
  - name: nextcloud-config
    namespace: nextcloud
    path: /data/apps/nextcloud/nextcloud/config
    size: 1Gi
  - name: nextcloud-data
    namespace: nextcloud
    path: /data/apps/nextcloud/nextcloud/data
    size: 500Gi
    accessMode: ReadWriteMany

  # PostgreSQL
  - name: infra-postgres-data
    namespace: infra
    path: /data/apps/infra/postgres-operator/data
    size: 8Gi

  # oCIS
  - name: owncloud-ocis-config
    namespace: owncloud
    path: /data/apps/owncloud/ocis/config
    size: 1Gi
  - name: owncloud-ocis-data
    namespace: owncloud
    path: /data/apps/owncloud/ocis/data
    size: 500Gi
    accessMode: ReadWriteMany

  # Infrastructure
  - name: infra-traefik-config
    namespace: infra
    path: /data/apps/infra/traefik/config
    size: 1Gi
