apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: seerr-tailscale
  annotations:
    tailscale.com/funnel: "true"
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
    - seerr
  defaultBackend:
    service:
      name: {{ include "common.names.fullname" . }}
      port:
        number: {{ .Values.seerr.service.port }}
