upbrr:
  image:
    repository: ghcr.io/autobrr/upbrr
    tag: latest
    pullPolicy: Always

  env:
    TZ: Etc/UTC

  service:
    type: LoadBalancer
    loadBalancerIP: 10.0.1.17
    port: 80
    containerPort: 7480

  persistence:
    config:
      enabled: true
      existingClaim: media-upbrr-config-pvc
    data:
      enabled: true
      existingClaim: media-shared-data-pvc

  ingressTargets:
    duckdns:
      host: upbrr.epricesx.duckdns.org
