apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard-local
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`192.168.1.111`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
    kind: Rule
    services:
    - name: api@internal
      kind: TraefikService
  tls: {}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard-duckdns
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`traefik.epricesx.duckdns.org`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
    kind: Rule
    services:
    - name: api@internal
      kind: TraefikService
  tls:
    certResolver: letsencrypt
    domains:
    - main: traefik.epricesx.duckdns.org
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: traefik-dashboard-freemyip
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`traefik.lmtu.freemyip.com`) && (PathPrefix(`/dashboard`) || PathPrefix(`/api`))
    kind: Rule
    services:
    - name: api@internal
      kind: TraefikService
  tls:
    certResolver: freemyip
    domains:
    - main: traefik.lmtu.freemyip.com
