apiVersion: v1
kind: Secret
metadata:
  name: dns-tokens
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  DUCKDNS_TOKEN: "cGxhY2Vob2xkZXI=" # value: placeholder
  FREEMYIP_TOKEN: "cGxhY2Vob2xkZXI=" # value: placeholder