{{- range $name, $cert := .Values.certificates }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: lego-{{ $name }}-on-sync
  namespace: {{ $.Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  template:
    spec:
      restartPolicy: OnFailure
      serviceAccountName: lego
      containers:
        - name: issue-cert
          image: alpine:3.20
          command: ["/bin/sh", "/scripts/issue-cert.sh"]
          env:
            - name: LEGO_EMAIL
              value: {{ $.Values.lego.email | quote }}
            - name: LEGO_VERSION
              value: {{ $.Values.lego.legoVersion | quote }}
            - name: KUBECTL_VERSION
              value: {{ $.Values.lego.kubectlVersion | quote }}
            - name: LEGO_PROVIDER
              value: {{ $cert.provider | quote }}
            - name: LEGO_DOMAINS
              value: {{ join " " $cert.domains | quote }}
            - name: LEGO_CERT_FILE_STEM
              value: {{ $cert.certFileStem | quote }}
            - name: SECRET_NAME
              value: {{ $cert.secretName | quote }}
            - name: NAMESPACE
              value: {{ $.Release.Namespace | quote }}
          envFrom:
            {{- toYaml $cert.envFrom | nindent 12 }}
          volumeMounts:
            - name: scripts
              mountPath: /scripts
              readOnly: true
            - name: lego-storage
              mountPath: /lego-storage
      volumes:
        - name: scripts
          configMap:
            name: lego-scripts
            defaultMode: 0755
        - name: lego-storage
          persistentVolumeClaim:
            claimName: {{ $.Values.lego.existingClaim }}
{{- end }}
