apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: {{ .Values.rtorrent.service.type | default "ClusterIP" }}
  {{- if .Values.rtorrent.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.rtorrent.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.rtorrent.service.port }}
      targetPort: rutorrent
      protocol: TCP
      name: rutorrent
    - port: 8000
      targetPort: xmlrpc
      protocol: TCP
      name: xmlrpc
    - port: 9000
      targetPort: webdav
      protocol: TCP
      name: webdav
    - port: 6881
      targetPort: dht
      protocol: UDP
      name: dht
    - port: 50000
      targetPort: incoming
      protocol: TCP
      name: incoming
  selector:
    {{- include "common.labels.selector" . | nindent 4 }}
