apiVersion: v2
name: infra-postgresql
description: PostgreSQL database for infrastructure and apps
type: application
version: 1.0.0
appVersion: "16.1.0"
dependencies:
  - name: postgresql
    version: 13.x.x
    repository: oci://registry-1.docker.io/bitnamicharts
