image:
  repository: postgres
  tag: 15-alpine # Using a pinned alpine version for stability and size
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5432

env:
  POSTGRES_DB: nextcloud
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: nextcloudpassword
  PGDATA: /var/lib/postgresql/data/pgdata

persistence:
  enabled: true
  existingClaim: infra-postgres-data-pvc
  mountPath: /var/lib/postgresql/data

resources:
  requests:
    memory: 256Mi
    cpu: 100m
  limits:
    memory: 512Mi
    cpu: 500m
