postgresql:
  image:
    repository: bitnami/postgresql
    tag: "16.1.0-debian-11-r25"
    digest: null

  auth:
    postgresPassword: "adminpassword"
    username: "nextcloud"
    password: "nextcloudpassword"
    database: "nextcloud"

  primary:
    persistence:
      enabled: true
      storageClass: "local-storage"
      size: 8Gi
    service:
      type: ClusterIP
      ports:
        postgresql: 5432

  volumePermissions:
    enabled: false
