postgresql:
  global:
    postgresql:
      auth:
        postgresPassword: "adminpassword"
        username: "nextcloud"
        password: "nextcloudpassword"
        database: "nextcloud"

  image:
    registry: docker.io
    repository: bitnami/postgresql
    tag: "16.1.0-debian-11"

  primary:
    persistence:
      enabled: true
      storageClass: "local-storage"
      size: 8Gi
    service:
      type: ClusterIP
      ports:
        postgresql: 5432

  volumePermissions:
    enabled: false
