apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  type: {{ .Values.deluge.service.type | default "ClusterIP" }}
  {{- if .Values.deluge.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.deluge.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.deluge.service.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: 58846
      targetPort: daemon
      protocol: TCP
      name: daemon
    - port: 6881
      targetPort: incoming-tcp
      protocol: TCP
      name: incoming-tcp
    - port: 6881
      targetPort: incoming-udp
      protocol: UDP
      name: incoming-udp
  selector:
    {{- include "common.labels.selector" . | nindent 4 }}
