profilarr:
  image:
    repository: ghcr.io/dictionarry-hub/profilarr
    tag: latest
    pullPolicy: Always
  env:
    TZ: Etc/UTC
    PUID: 1000
    PGID: 1000
    UMASK: "022"
    ORIGIN: https://profilarr.epricesx.duckdns.org

  service:
    type: ClusterIP
    port: 6868

  persistence:
    config:
      enabled: true
      existingClaim: media-profilarr-config-pvc

  ingressTargets:
    duckdns:
      host: profilarr.epricesx.duckdns.org
      certResolver: letsencrypt
    freemyip:
      host: profilarr.lmtu.freemyip.com
      certResolver: freemyip
      tlsDomain: "*.lmtu.freemyip.com"
      tlsSans:
        - lmtu.freemyip.com
    myaddr:
      host: profilarr.lmtlmt.myaddr.io
      certResolver: myaddr
