argo-cd:
  global:
    domain: argo.epricesx.duckdns.org
  configs:
    cm:
      url: https://argo.epricesx.duckdns.org
      exec.enabled: "true"
    params:
      server.insecure: "true"
  server:
    insecure: true
    extraArgs:
      - --insecure
    service:
      type: ClusterIP
    ingress:
      enabled: false

ingressTargets:
  duckdns:
    host: argo.epricesx.duckdns.org
    certResolver: letsencrypt
  freemyip:
    host: argo.lmtu.freemyip.com
    certResolver: freemyip
  myaddr:
    host: argo.lmtlmt.myaddr.io
    certResolver: myaddr
  local-ip:
    host: "192.168.1.111"
    certResolver: ""