argo-cd:
  configs:
    cm:
      url: "" # Explicitly empty to support multi-domain access
      exec.enabled: "true"
  server:
    insecure: false
    service:
      type: ClusterIP
    ingress:
      enabled: false

ingressTargets:
  duckdns:
    host: argo.epricesx.duckdns.org
    certResolver: letsencrypt
  freemyip:
    host: argo.lmtu.freemyip.com
    certResolver: freemyip
  myaddr:
    host: argo.lmtlmt.myaddr.io
    certResolver: myaddr
  local-ip:
    host: "192.168.1.111"
    certResolver: ""