apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sonarr-tailscale
  annotations:
    tailscale.com/funnel: "true"
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
    - sonarr
  defaultBackend:
    service:
      name: {{ .Release.Name }}
      port:
        number: 8989
