bazarr:
  image:
    repository: lscr.io/linuxserver/bazarr
    tag: latest
    pullPolicy: IfNotPresent
  env:
    TZ: Etc/UTC
    PUID: 1000
    PGID: 1000
  
  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.155
    port: 6767

  persistence:
    config:
      enabled: true
      existingClaim: media-bazarr-config-pvc
    movies:
      enabled: true
      existingClaim: media-shared-movies-pvc
      mountPath: /movies
    shows:
      enabled: true
      existingClaim: media-shared-shows-pvc
      mountPath: /tv
  
  ingressTargets:
    duckdns:
      host: bazarr.epricesx.duckdns.org
      certResolver: letsencrypt
    freemyip:
      host: bazarr.lmtu.freemyip.com
      certResolver: freemyip
      tlsDomain: "*.lmtu.freemyip.com"
      tlsSans:
        - lmtu.freemyip.com
    myaddr:
      host: bazarr.lmtlmt.myaddr.io
      certResolver: myaddr
