bazarr:
  image:
    repository: lscr.io/linuxserver/bazarr
    tag: latest
    pullPolicy: Always
  env:
    TZ: Etc/UTC
    PUID: 1000
    PGID: 1000
  
  service:
    type: LoadBalancer
    loadBalancerIP: 10.0.1.6
    port: 80

  persistence:
    config:
      enabled: true
      existingClaim: media-bazarr-config-pvc
    data:
      enabled: true
      existingClaim: media-shared-data-pvc
      mountPath: /data
  
  ingressTargets:
    duckdns:
      host: bazarr.epricesx.duckdns.org
    freemyip:
      host: bazarr.lmtu.freemyip.com
    myaddr:
      host: bazarr.lmtlmt.myaddr.io
