q3:
  image:
    repository: lscr.io/linuxserver/qbittorrent
    tag: latest
    pullPolicy: Always

  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.166
    port: 8080

  persistence:
    config:
      enabled: true
      existingClaim: media-q3-config-pvc
    data:
      enabled: true
      existingClaim: media-shared-data-pvc
      mountPath: /data

  ingressTargets:
    duckdns:
      host: q3.epricesx.duckdns.org
      certResolver: letsencrypt
    freemyip:
      host: q3.lmtu.freemyip.com
      certResolver: freemyip
      tlsDomain: "*.lmtu.freemyip.com"
      tlsSans:
        - lmtu.freemyip.com
    myaddr:
      host: q3.lmtlmt.myaddr.io
      certResolver: myaddr
