traefik:
  service:
    enabled: true
    single: true
    type: LoadBalancer
    spec:
      loadBalancerIP: "192.168.1.111"
  persistence:
    enabled: true
    existingClaim: infra-traefik-config-pvc
    size: 1Gi
    path: /data
  envFrom:
    - secretRef:
        name: duckdns-secret
    - secretRef:
        name: freemyip-secret
    - secretRef:
        name: myaddr-secret
  providers:
    kubernetesCRD:
      enabled: true
      allowCrossNamespace: true
    kubernetesIngress:
      enabled: true
      publishedService:
        enabled: true
  podSecurityContext:
    runAsGroup: 1000
    runAsUser: 1000
    fsGroup: 1000
  securityContext:
    runAsGroup: 1000
    runAsUser: 1000
    readOnlyRootFilesystem: false
    capabilities:
      drop:
        - ALL
      add:
        - NET_BIND_SERVICE
  additionalArguments:
    - "--certificatesresolvers.letsencrypt.acme.storage=/data/duckdns.json"
    - "--certificatesresolvers.letsencrypt.acme.email=mt.the.dev@gmail.com"
    - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=duckdns"
    - "--certificatesresolvers.freemyip.acme.storage=/data/freemyip.json"
    - "--certificatesresolvers.freemyip.acme.email=mt.the.dev@gmail.com"
    - "--certificatesresolvers.freemyip.acme.dnschallenge.provider=duckdns"
    - "--certificatesresolvers.myaddr.acme.storage=/data/myaddr.json"
    - "--certificatesresolvers.myaddr.acme.email=mt.the.dev@gmail.com"
    - "--certificatesresolvers.myaddr.acme.dnschallenge.provider=duckdns"
    # Enable Dashboard (Insecure mode for internal access, or use IngressRoute to secure)
    - "--api.dashboard=true"
    - "--api.insecure=true"
  ports:
    web:
      http:
        redirections:
          entryPoint:
            to: websecure
            scheme: https
            permanent: true
    websecure:
      http:
        tls:
          enabled: true
          certResolver: letsencrypt
          domains:
            - main: epricesx.duckdns.org
              sans: ["*.epricesx.duckdns.org"]
    traefik:
      port: 8080
      expose:
        default: true
      exposedPort: 8080
      protocol: TCP

ingressTargets:
  local-ip:
    host: "192.168.1.111"
    path: "/dashboard"
    stripPrefix: false
  duckdns:
    host: "traefik.epricesx.duckdns.org"
    certResolver: letsencrypt
  freemyip:
    host: "traefik.lmtu.freemyip.com"
    certResolver: freemyip
  myaddr:
    host: "traefik.lmtlmt.myaddr.io"
    certResolver: myaddr