sonarr:
  image:
    repository: lscr.io/linuxserver/sonarr
    tag: latest
  service:
    main:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.150
  env:
    TZ: Etc/UTC
    PUID: 1000
    PGID: 1000
  
  ingressTargets:
    duckdns:
      host: sonarr.epricesx.duckdns.org
      certResolver: letsencrypt
    freemyip:
      host: sonarr.lmtu.freemyip.com
      certResolver: freemyip
      tlsDomain: "*.lmtu.freemyip.com"
      tlsSans:
        - lmtu.freemyip.com
    myaddr:
      host: lmtlmt.myaddr.io
      certResolver: myaddr

  persistence:
    config:
      enabled: true
      existingClaim: sonarr-config-pvc
    tv:
      enabled: true
      existingClaim: shows-pvc
      mountPath: /tv
    downloads:
      enabled: true
      existingClaim: downloads-pvc
      mountPath: /downloads
  ingress:
    main:
      enabled: false
