sonarr:
  image:
    repository: lscr.io/linuxserver/sonarr
    tag: latest
  env:
    TZ: Etc/UTC
    PUID: 1000
    PGID: 1000
  
  ingressTargets:
    duckdns:
      host: sonarr.epricesx.duckdns.org
      certResolver: letsencrypt
    freemyip:
      host: sonarr.lmtu.freemyip.com
      certResolver: freemyip
    myaddr:
      host: lmtlmt.myaddr.io
      certResolver: myaddr

  persistence:
    config:
      enabled: true
      existingClaim: sonarr-config-pvc
    tv:
      enabled: true
      existingClaim: sonarr-tv-pvc
      mountPath: /tv
    downloads:
      enabled: true
      existingClaim: sonarr-downloads-pvc
      mountPath: /downloads
  ingress:
    main:
      enabled: false
