sonarr:
  image:
    repository: lscr.io/linuxserver/sonarr
    tag: latest
    pullPolicy: Always
  service:
    type: LoadBalancer
    loadBalancerIP: 10.0.1.16
    port: 80
  env:
    TZ: Etc/UTC
    PUID: 1000
    PGID: 1000

  ingressTargets:
    duckdns:
      host: sonarr.epricesx.duckdns.org
    freemyip:
      host: sonarr.lmtu.freemyip.com
    myaddr:
      host: sonarr.lmtlmt.myaddr.io

  persistence:
    config:
      enabled: true
      existingClaim: media-sonarr-config-pvc
    data:
      enabled: true
      existingClaim: media-shared-data-pvc
      mountPath: /data
