rtorrent:
  image:
    repository: crazymax/rtorrent-rutorrent
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.165
    port: 8080

  persistence:
    data:
      enabled: true
      existingClaim: media-rtorrent-data-pvc
    downloads:
      enabled: true
      existingClaim: media-shared-downloads-pvc
      mountPath: /downloads
    passwd:
      enabled: true
      existingClaim: media-rtorrent-passwd-pvc

  ingressTargets:
    duckdns:
      host: rtorrent.epricesx.duckdns.org
      certResolver: letsencrypt
    freemyip:
      host: rtorrent.lmtu.freemyip.com
      certResolver: freemyip
      tlsDomain: "*.lmtu.freemyip.com"
      tlsSans:
        - lmtu.freemyip.com
    myaddr:
      host: rtorrent.lmtlmt.myaddr.io
      certResolver: myaddr
