apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud
  labels:
    app.kubernetes.io/name: nextcloud
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: nextcloud
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nextcloud
    spec:
      initContainers:
        - name: init-permissions
          image: busybox
          command: ['sh', '-c', 'mkdir -p /mnt/html /mnt/data && chown -R 33:33 /mnt/html /mnt/data']
          volumeMounts:
            - name: nextcloud-app
              mountPath: /mnt
      containers:
        - name: nextcloud
          image: "{{ .Values.nextcloud.image.repository }}:{{ .Values.nextcloud.image.tag }}"
          imagePullPolicy: {{ .Values.nextcloud.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: NEXTCLOUD_TRUSTED_DOMAINS
              value: "{{ range $name, $target := .Values.nextcloud.ingressTargets }}{{ $target.host }} {{ end }}"
            - name: TRUSTED_PROXIES
              value: "10.0.0.0/8 172.16.0.0/12 192.168.0.0/16"
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db-app
                  key: dbname
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db-app
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db-app
                  key: password
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: nextcloud-db-app
                  key: host
          volumeMounts:
            - name: nextcloud-app
              mountPath: /var/www/html
              subPath: html
            - name: nextcloud-app
              mountPath: /var/www/html/data
              subPath: data
            - name: host-data
              mountPath: /host-data
      volumes:
        - name: nextcloud-app
          persistentVolumeClaim:
            claimName: {{ .Values.nextcloud.persistence.app.existingClaim }}
        - name: host-data
          persistentVolumeClaim:
            claimName: {{ .Values.nextcloud.persistence.hostData.existingClaim }}