q2:
  image:
    repository: lscr.io/linuxserver/qbittorrent
    tag: 5.1.4
    pullPolicy: Always

  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.165
    port: 8080

  persistence:
    config:
      enabled: true
      existingClaim: media-q2-config-pvc
    downloads:
      enabled: true
      existingClaim: media-shared-downloads-pvc
      mountPath: /downloads

  ingressTargets:
    duckdns:
      host: q2.epricesx.duckdns.org
      certResolver: letsencrypt
    freemyip:
      host: q2.lmtu.freemyip.com
      certResolver: freemyip
      tlsDomain: "*.lmtu.freemyip.com"
      tlsSans:
        - lmtu.freemyip.com
    myaddr:
      host: q2.lmtlmt.myaddr.io
      certResolver: myaddr
