image:
  repository: owncloud/ocis
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9200

env:
  OCIS_INSECURE: "true"
  PROXY_HTTP_ADDR: "0.0.0.0:9200"
  OCIS_URL: "https://ocis.epricesx.duckdns.org"

persistence:
  config:
    enabled: true
    existingClaim: ocis-config-v2-pvc
  data:
    enabled: true
    existingClaim: ocis-data-v2-pvc

ingressTargets:
  duckdns:
    host: ocis.epricesx.duckdns.org
    certResolver: letsencrypt