apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "common.labels.selector" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.labels.selector" . | nindent 8 }}
    spec:
      containers:
        - name: qbittorrent
          image: "{{ .Values.qbittorrent.image.repository }}:{{ .Values.qbittorrent.image.tag }}"
          imagePullPolicy: {{ .Values.qbittorrent.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.qbittorrent.service.port }}
              protocol: TCP
            - name: bittorrent
              containerPort: 6881
              protocol: TCP
              
          env:
            {{- range $key, $value := .Values.qbittorrent.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          
          volumeMounts:
            {{- if .Values.qbittorrent.persistence.config.enabled }}
            - name: config
              mountPath: /config
            {{- end }}
            {{- if .Values.qbittorrent.persistence.downloads.enabled }}
            - name: downloads
              mountPath: {{ .Values.qbittorrent.persistence.downloads.mountPath }}
            {{- end }}
      
      volumes:
        {{- if .Values.qbittorrent.persistence.config.enabled }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ .Values.qbittorrent.persistence.config.existingClaim }}
        {{- end }}
        {{- if .Values.qbittorrent.persistence.downloads.enabled }}
        - name: downloads
          persistentVolumeClaim:
            claimName: {{ .Values.qbittorrent.persistence.downloads.existingClaim }}
        {{- end }}
