apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbittorrent-tailscale
  annotations:
    tailscale.com/funnel: "true"
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
    - qbittorrent
  defaultBackend:
    service:
      name: {{ include "common.names.fullname" . }}
      port:
        number: {{ .Values.qbittorrent.service.port }}
