nextcloud:
  image:
    repository: nextcloud
    tag: latest
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 80

  persistence:
    app:
      enabled: true
      existingClaim: nextcloud-app-pvc
    hostData:
      enabled: true
      existingClaim: nextcloud-host-data-pvc

  ingressTargets:
    duckdns:
      host: nextcloud.epricesx.duckdns.org
      certResolver: letsencrypt
    freemyip:
      host: nextcloud.lmtu.freemyip.com
      certResolver: freemyip
      tlsDomain: "*.lmtu.freemyip.com"
      tlsSans:
        - lmtu.freemyip.com
    myaddr:
      host: nextcloud.lmtlmt.myaddr.io
      certResolver: myaddr