apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: homepage
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  services.yaml: |
    {{- toYaml .Values.config.services | nindent 4 }}
  widgets.yaml: |
    {{- toYaml .Values.config.widgets | nindent 4 }}
  settings.yaml: |
    {{- toYaml .Values.config.settings | nindent 4 }}
