{{- range $name, $target := .Values.ingressTargets }}
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: homepage-{{ $name }}
  namespace: {{ $.Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`{{ $target.host }}`)
    kind: Rule
    services:
    - name: homepage
      port: 3000
  tls:
    {{- if $target.certResolver }}
    certResolver: {{ $target.certResolver }}
    {{- else }}
    {}
    {{- end }}
{{- end }}
