apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage-tailscale
  annotations:
    tailscale.com/funnel: "true"
spec:
  ingressClassName: tailscale
  tls:
  - hosts:
    - homepage
  defaultBackend:
    service:
      name: homepage
      port:
        number: 3000
