apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "common.labels.selector" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "common.labels.selector" . | nindent 8 }}
    spec:
      containers:
        - name: profilarr
          image: "{{ .Values.profilarr.image.repository }}:{{ .Values.profilarr.image.tag }}"
          imagePullPolicy: {{ .Values.profilarr.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.profilarr.service.containerPort }}
              protocol: TCP

          env:
            {{- range $key, $value := .Values.profilarr.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}

          volumeMounts:
            {{- if .Values.profilarr.persistence.config.enabled }}
            - name: config
              mountPath: /config
            {{- end }}

      volumes:
        {{- if .Values.profilarr.persistence.config.enabled }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ .Values.profilarr.persistence.config.existingClaim }}
        {{- end }}
