prowlarr:
  image:
    repository: lscr.io/linuxserver/prowlarr
    tag: latest
    pullPolicy: Always
  env:
    TZ: Etc/UTC
    PUID: 1000
    PGID: 1000
  
  service:
    type: LoadBalancer
    loadBalancerIP: 10.0.1.9
    port: 80

  persistence:
    config:
      enabled: true
      existingClaim: media-prowlarr-config-pvc
  
  ingressTargets:
    duckdns:
      host: prowlarr.epricesx.duckdns.org
    freemyip:
      host: prowlarr.lmtu.freemyip.com
    myaddr:
      host: prowlarr.lmtlmt.myaddr.io
