transmission:
  image:
    repository: lscr.io/linuxserver/transmission
    tag: latest
    pullPolicy: IfNotPresent
  env:
    TZ: Etc/UTC
    PUID: 1000
    PGID: 1000
    USER: ''
    PASS: ''
  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.159
    port: 9091
  persistence:
    config:
      enabled: true
      existingClaim: media-t1-config-pvc
    downloads:
      enabled: true
      existingClaim: media-shared-downloads-pvc
      mountPath: /downloads
  ingressTargets:
    duckdns:
      host: t1.epricesx.duckdns.org
      certResolver: letsencrypt
    freemyip:
      host: t1.lmtu.freemyip.com
      certResolver: freemyip
      tlsDomain: '*.lmtu.freemyip.com'
      tlsSans:
      - lmtu.freemyip.com
    myaddr:
      host: t1.lmtlmt.myaddr.io
      certResolver: myaddr
