targetNamespaces:
  - infra

secrets:
  duckdns-secret:
    data:
      DUCKDNS_TOKEN: "MjQyZDFmYTgtMzI2ZS00MmZmLTkyYTgtNWZmYjJkN2QyYzM0"
  freemyip-secret:
    data:
      FREEMYIP_TOKEN: "NDNkODE1MWExMDI3MjU2MmQyMTU3NWMw"
  myaddr-secret:
    data:
      # Key for DDNS updater script
      MYADDR_KEY: "NjU3NWVhYWE5OWUxNTVmZGRlMTViMGVkMDM4ZjNhMGNhMDRjOTA4Y2M3N2MyNDQ2YzE2NDk1Y2UxOGNlZGUxMg=="
      # Mapping for Traefik/Lego: subdomain:private_key
      MYADDR_PRIVATE_KEYS_MAPPING: "bG10bG10OjY1NzVlYWFhOTllMTU1ZmRkZTE1YjBlZDAzOGYzYTBjYTA0YzkwOGNjNzdjMjQ0NmMxNjQ5NWNlMThjZWRlMTI="