q1:
  image:
    repository: lscr.io/linuxserver/qbittorrent
    tag: latest
    pullPolicy: Always

  service:
    type: LoadBalancer
    loadBalancerIP: 10.0.1.10
    port: 80

  persistence:
    config:
      enabled: true
      existingClaim: media-q1-config-pvc
    data:
      enabled: true
      existingClaim: media-shared-data-pvc
      mountPath: /data

  ingressTargets:
    duckdns:
      host: q1.epricesx.duckdns.org
    freemyip:
      host: q1.lmtu.freemyip.com
    myaddr:
      host: q1.lmtlmt.myaddr.io
