qui:
  image:
    repository: ghcr.io/autobrr/qui
    tag: latest
    pullPolicy: Always

  env:
    TZ: "Etc/UTC"

  service:
    type: LoadBalancer
    loadBalancerIP: 192.168.1.156
    port: 7476

  persistence:
    config:
      enabled: true
      existingClaim: media-qui-config-pvc
    downloads:
      enabled: true
      existingClaim: media-shared-downloads-pvc
      mountPath: /downloads
    movies:
      enabled: true
      existingClaim: media-shared-movies-pvc
      mountPath: /movies
    shows:
      enabled: true
      existingClaim: media-shared-shows-pvc
      mountPath: /shows

  ingressTargets:
    duckdns:
      host: qui.epricesx.duckdns.org
      certResolver: letsencrypt
    freemyip:
      host: qui.lmtu.freemyip.com
      certResolver: freemyip
      tlsDomain: "*.lmtu.freemyip.com"
      tlsSans:
        - lmtu.freemyip.com
    myaddr:
      host: qui.lmtlmt.myaddr.io
      certResolver: myaddr
